sm8350-common: Add missing manifest
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.samsung.hardware.health@2.0::ISehHealth/default
    vendor.samsung.hardware.keymint.ISehKeyMintExtension/default (@2)
    vendor.samsung.hardware.keymint.ISehKeyMintFactory/default (@2)